### ISSUE TITLE
French translation not working

### ISSUE THREAD

**Issue by Zamarza** [carcam/plg_readingtime#19]
Hello,

thank you for your great and useful extension. Easy to use.

I got a problem. My website is in English and French. The translation is not working in French. I must override PLG_READINGTIME_LABEL in French to get it displayed correctly.

Do you know the translation does not work? Would you tell me where the file in French should be located?

Thanks for your help
Sincerely
Amar Guillen

**Comment by carcam** [comment]
Hi Zamarza,
that's is weird. It's very likely there is an error in the language file. I'm going to test this and will come back with a solution or requesting more info.

Thank you very much for useing Estimated Reading Time!!

**Comment by Zamarza** [comment]
Hello,

 

Thank your reply.

I will wait for a solution.

If you need to make a test, I have a test website. I can give you access.

 

Sincerely
Amar Guillen

 

 <https://www.guillenphoto.com/>  

Amar Guillen: The Passion for the Wonders of Nature.

 

Reconnect to Nature with my Fine Art Prints.

 

Website: https://www.guillenphoto.com <https://www.guillenphoto.com/> 

 

Phone: (+1) 214-769-6825
Email:  <mailto:contact@guillenphoto.com> contact@guillenphoto.com

Skype : guillenphoto

 

 <https://www.instagram.com/amarguillen/>    <https://www.facebook.com/amarguillen>    <https://www.linkedin.com/in/amarguillen>

**Comment by carcam** [comment]
I have just published 3.6.2 release which should fix this issue. Please open a new ticket otherwise:

https://extensions.hepta.es/downloads/estimated-reading-time/estimated-reading-time-3-6-2?format=html

Best!!

**Comment by Zamarza** [comment]
Thank you Carlos,

 

I installed the last version. The problem still occurs.

Really I thing it is a conjunction of facts that creates the problem.

 

I am working with two different browsers now. It works.

Sincelery
Amar

 

 <https://www.guillenphoto.com/>  

Amar Guillen: The Passion for the Wonders of Nature.

 

Reconnect to Nature with my Fine Art Prints.

 

Website: https://www.guillenphoto.com <https://www.guillenphoto.com/> 

 

Phone: (+1) 214-769-6825
Email:  <mailto:contact@guillenphoto.com> contact@guillenphoto.com

Skype : guillenphoto

 

 <https://www.instagram.com/amarguillen/>    <https://www.facebook.com/amarguillen>    <https://www.linkedin.com/in/amarguillen>

**Comment by carcam** [comment]
Hi Amar,
it was me not doing a proper release...

I have fixed it in your site and in the published release and now it speaks french ;).

Best!!

**Comment by Zamarza** [comment]
I am still have the same behaviour. I am logged out every time.
Amar

 

 <https://www.guillenphoto.com/>  

Amar Guillen: The Passion for the Wonders of Nature.

 

Reconnect to Nature with my Fine Art Prints.

 

Website: https://www.guillenphoto.com <https://www.guillenphoto.com/> 

 

Phone: (+1) 214-769-6825
Email:  <mailto:contact@guillenphoto.com> contact@guillenphoto.com

Skype : guillenphoto

 

 <https://www.instagram.com/amarguillen/>    <https://www.facebook.com/amarguillen>    <https://www.linkedin.com/in/amarguillen>

**Comment by carcam** [comment]
You are testing in the dev site, right? Also, please be sure you choose the French language ;)

**Comment by Zamarza** [comment]
Thank you Carlos.

 

It works fine in the dev site.

 

I am using Chrome. I cleared all the cache files. And now it works well.

 

Can I download the version from GitHub to install it in my production site?

 

If the problem was coming from the plugin, do you know when I have uninstalled it, I still had the problem?

 

Let me know if I have the ‘go’ for my prod site.

 

Sincerely
Amar

 

 <https://www.guillenphoto.com/>  

Amar Guillen: The Passion for the Wonders of Nature.

 

Reconnect to Nature with my Fine Art Prints.

 

Website: https://www.guillenphoto.com <https://www.guillenphoto.com/> 

 

Phone: (+1) 214-769-6825
Email:  <mailto:contact@guillenphoto.com> contact@guillenphoto.com

Skype : guillenphoto

 

 <https://www.instagram.com/amarguillen/>    <https://www.facebook.com/amarguillen>    <https://www.linkedin.com/in/amarguillen>

**Comment by carcam** [comment]
Just paste this link in the "install from URL" thing:

https://extensions.hepta.es/downloads/estimated-reading-time/estimated-reading-time-3-6-2/plg_content_readingtime_3-6-2-zip?format=zip

and it will work for your production site ;)

**Comment by Zamarza** [comment]
Hello Carlos,

 

It works well. Thank you very much.

 

You are very good.

 

Finally, the reason of my problem was the plugin. I still do not understand why but you find a solution. I am so happy.

 

You are very persistent. Thank you for having solved my problem.

Great extension.

 

All my best
Amar

 

 <https://www.guillenphoto.com/>  

Amar Guillen: The Passion for the Wonders of Nature.

 

Reconnect to Nature with my Fine Art Prints.

 

Website: https://www.guillenphoto.com <https://www.guillenphoto.com/> 

 

Phone: (+1) 214-769-6825
Email:  <mailto:contact@guillenphoto.com> contact@guillenphoto.com

Skype : guillenphoto

 

 <https://www.instagram.com/amarguillen/>    <https://www.facebook.com/amarguillen>    <https://www.linkedin.com/in/amarguillen>

**Comment by carcam** [comment]
Thank you very much!! Will appreciate a lot if you can find some time to leave a review at JED ;) It helps other people to discover the plugin too ;)

Best!!

**Comment by Zamarza** [comment]
I did.

 

Thanks for all
Amar

 

 <https://www.guillenphoto.com/>  

Amar Guillen: The Passion for the Wonders of Nature.

 

Reconnect to Nature with my Fine Art Prints.

 

Website: https://www.guillenphoto.com <https://www.guillenphoto.com/> 

 

Phone: (+1) 214-769-6825
Email:  <mailto:contact@guillenphoto.com> contact@guillenphoto.com

Skype : guillenphoto

 

 <https://www.instagram.com/amarguillen/>    <https://www.facebook.com/amarguillen>    <https://www.linkedin.com/in/amarguillen>
